from tkinter import *
from tkinter import ttk
import random
to_number = {chr(i + 97): i for i in range(26)}
to_letter = {v: k for k, v in to_number.items()}
atbash = {
    'a':'z', 'b':'y', 'c':'x', 'd':'w', 'e':'v', 'f':'u',
    'g':'t', 'h':'s', 'i':'r', 'j':'q', 'k':'p', 'l':'o',
    'm':'n', 'n':'m', 'o':'l', 'p':'k', 'q':'j', 'r':'i',
    's':'h', 't':'g', 'u':'f', 'v':'e', 'w':'d', 'x':'c',
    'y':'b', 'z':'a'
}
caeser_description="A Ceaser cipher encrypts by shifting each letter k amounts around the alphabet. For emaple, in a key of 1 A=B. To decrypt the cipher simply do k amounts of shifts the other way."
affine_description="The Affine Cipher is a substitution cipher wherein each letter in an alphabet is mapped to its numeric equivalent using the formula E(X) = (aX + b) mod 26. X repesents each letter and a, b represnts the cipher key such that a is relatively prime to 26 (gcd(a, 26)=1), and b is the shift value."
vigenère_description="The Vigenère Cipher is a polyalphabetic substitution cipher that uses a keyword or phrase to encrypt the plaintext by shifting the letters to the corresponding letter of the key."
rail_fence_description="The plaintext is written diagonally across a number of 'rails' (horizontal lines), and the ciphertext is formed by reading the rails then taking each one and adding it one by one to the ciphertext."
atbash_description="An ancient hewbrew cypher, and a simple one, the alphabet is mapped backwords so A=Z, B=Y, C=X and so on."
row_transposition_description="The plaintext is written into a grid row by row, and then the ciphertext is generated by reading the columns in a specific order determined by a key."

def caesar_e(plaintext,key):
    plaintext = plaintext.lower().replace(" ", "")
    key=int(key)
    ciphertext=""
    for i in plaintext:
        if i.isalpha():
            x=to_number[i]
            x=(x+key)%26
            x=to_letter[x]
            ciphertext+=x
        else:
            ciphertext+=i
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)

def affine_e(plaintext,ab):
    plaintext = plaintext.lower().replace(" ", "")
    a, b=ab.split(",")
    a=int(a)
    b=int(b)
    ciphertext=""
    for i in plaintext:
        if i.isalpha():
            x=to_number[i]
            x=(a*x+b)%26
            x=to_letter[x]
            ciphertext+=x
        else:
            ciphertext+=i
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)
    
def vigenère_e(plaintext,keyword):
    plaintext = plaintext.lower().replace(" ", "")
    keyword=keyword.lower().replace(" ", "")
    key=[]
    for i in keyword:
        x=to_number[i]
        key.append(x)
    ciphertext=""
    for i in range(len(plaintext)):
        if plaintext[i].isalpha():
            x = to_number[plaintext[i]]
            x = (x + key[i % len(key)]) % 26
            x = to_letter[x]
            ciphertext += x
        else:
            ciphertext+=plaintext[i]
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)

def rail_fence_e(plaintext,rail):
    plaintext=plaintext.lower().replace(" ", "")
    rail=int(rail)
    ciphertext=""
    rails=[[] for i in range(rail)]
    direction=1
    row=0
    for letter in plaintext:
        rails[row].append(letter)
        if row==0:
            direction=1
        elif row==rail-1:
            direction=-1
        row+=direction
    for r in rails:
        for c in r:
            ciphertext+=c
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)

def atbash_e(plaintext):
    plaintext = plaintext.lower().replace(" ", "")
    ciphertext=""
    for i in plaintext:
        if i.isalpha():
            x=atbash[i]
            ciphertext+=x
        else:
            ciphertext+=i
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)

def row_transposition_e(plaintext,key):
    plaintext=plaintext.lower().replace(" ", "")
    keylist=[]
    for i in key:
        keylist.append(int(i))
    ciphertext=""
    keys=[[] for i in range(len(keylist))]
    keys2=[[] for i in range(len(keylist))]
    max_key=max(keylist)
    iteration=0
    for i in plaintext:
        keys[iteration].append(i)
        iteration+=1
        if iteration==max_key:
            iteration=0
    for i in range (max_key):
        while len(keys[i]) < len(keys[0]):
            x=random.randint(0, 25)
            x=to_letter[x]
            keys[i].append(x)
    for i in range(len(keylist)):
        keys2[keylist[i]-1]=keys[i]
    for i in keys2:
        for j in i:
            ciphertext+=j
    ciphertextE.delete("1.0", "end")
    ciphertextE.insert("1.0", ciphertext)
    
def caesar_d(ciphertext, key):
    ciphertext = ciphertext.lower().replace(" ", "")
    plaintext=""
    key=int(key)
    for i in ciphertext:
        if i.isalpha():
            x=to_number[i]
            x=(x-key)%26
            x=to_letter[x]
            plaintext+=x
        else:
                plaintext+=i
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)

def mod_inverse(a, m):
    for i in range(m):
        if (a * i) % m == 1:
            return i

def affine_d(ciphertext,ab):
    ciphertext = ciphertext.lower().replace(" ", "")
    a, b=ab.split(",")
    a=int(a)
    b=int(b)
    plaintext=""
    a_inv = mod_inverse(a, 26)
    for i in ciphertext:
        if i.isalpha():
            x=to_number[i]
            x=(a_inv*(x-b))%26
            x=to_letter[x]
            plaintext+=x
        else:
                plaintext+=i
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)
    
def vigenère_d(ciphertext, keyword):
    ciphertext = ciphertext.lower().replace(" ", "")
    keyword=keyword.lower().replace(" ", "")
    key=[]
    for i in keyword:
        x=to_number[i]
        key.append(x)
    plaintext=""
    for i in range(len(ciphertext)):
        if ciphertext[i].isalpha():
            x = to_number[ciphertext[i]]
            x = (x - key[i % len(key)]) % 26
            x = to_letter[x]
            plaintext += x
        else:
                plaintext+=ciphertext[i]
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)

def rail_fence_d(ciphertext, rail):
    ciphertext=ciphertext.lower().replace(" ", "")
    rail=int(rail)
    pattern=[]
    row=0
    direction=1
    for i in range(len(ciphertext)):
        pattern.append(row)
        if row==0:
            direction=1
        elif row==rail-1:
            direction=-1
        row+=direction
    rails=[[] for i in range(rail)]
    index=0
    for r in range(rail):
        count=pattern.count(r)
        rails[r]=list(ciphertext[index:index+count])
        index+=count
    plaintext=""
    rail_index=[0]*rail
    for r in pattern:
        plaintext+=rails[r][rail_index[r]]
        rail_index[r]+=1
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)

def atbash_d(ciphertext):
    ciphertext = ciphertext.lower().replace(" ", "")
    plaintext=""
    for i in ciphertext:
        if i.isalpha():
            x=atbash[i]
            plaintext+=x
        else:
                plaintext+=i
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)

def row_transposition_d(ciphertext, key):
    ciphertext=ciphertext.lower().replace(" ", "")
    keylist=[]
    for i in key:
        keylist.append(int(i))
    plaintext=""
    keys=[[] for i in range(len(keylist))]
    keys2=[[] for i in range(len(keylist))]
    max_key=max(keylist)
    cols=len(keylist)
    rows=len(ciphertext)//cols
    iteration=0
    for i in range(cols):
        keys2[i]=list(ciphertext[iteration:iteration+rows])
        iteration+=rows
    for i in range(len(keylist)):
        keys[i]=keys2[keylist[i]-1]
    for r in range(rows):
        for c in range(len(keys)):
            plaintext+=keys[c][r]
    plaintextE.delete("1.0", "end")
    plaintextE.insert("1.0", plaintext)

def change_screen(event):
    choice = combo.get()
    if choice == "Ceaser Cipher":
        cyph.config(text=caeser_description,)
        keyL.config(text="Shift:")
        encryptB.config(command=lambda: caesar_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
        decryptB.config(command=lambda: caesar_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))
    
    elif choice=="Affine Cipher":
        cyph.config(text=affine_description)
        keyL.config(text="A and B value (please seperate with a comma:")
        encryptB.config(command=lambda: affine_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
        decryptB.config(command=lambda: affine_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))
        
    elif choice=="Vigenère Cipher":
        cyph.config(text=vigenère_description,)
        keyL.config(text="Keyword:")
        encryptB.config(command=lambda: vigenère_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
        decryptB.config(command=lambda: vigenère_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))
        
    elif choice=="Rail fence cipher":
        cyph.config(text=rail_fence_description,)
        keyL.config(text="Rails:")
        encryptB.config(command=lambda: rail_fence_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
        decryptB.config(command=lambda: rail_fence_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))
        
    elif choice=="Atbash cipher":
        cyph.config(text=atbash_description)
        keyL.config(text="N/A")
        encryptB.config(command=lambda: atbash_e(plaintextE.get("1.0", "end-1c")))
        decryptB.config(command=lambda: atbash_d(ciphertextE.get("1.0", "end-1c")))
        
    elif choice=="Row transposition cipher":
        cyph.config(text=row_transposition_description)
        keyL.config(text="Key")
        encryptB.config(command=lambda: row_transposition_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
        decryptB.config(command=lambda: row_transposition_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))
        
def delete():
    ciphertextE.delete("1.0", "end")
    plaintextE.delete("1.0", "end")

root=Tk()
root.title("Cryptography")
screen_width=root.winfo_screenwidth()
screen_height=root.winfo_screenheight()
root.geometry(f"{screen_width}x{screen_height}")
root.configure(bg="#FFE4C4")

options=["Ceaser Cipher", "Affine Cipher", "Vigenère Cipher", "Rail fence cipher", "Atbash cipher", "Row transposition cipher"]
combo=ttk.Combobox(root, values=options, state="readonly",font=("Arial", 12))
combo.current(0)
combo.grid(row=0, column=0, columnspan=2)


cyph=Label(root, text=caeser_description,font=("Arial", 14),wraplength=500,justify="left")
cyph.grid(row=1, column=0, columnspan=2)

frame = Frame(root)
frame.grid(row=2, column=0, columnspan=2)
keyL=Label(frame, text="Shift:", font=("Arial", 12))
keyL.grid(row=2, column=0, padx=0)
keyLg=Entry(frame)
keyLg.grid(row=2, column=1,padx=0)

plaintextL=Label(root, text="Plaintext", font=("Arial", 12))
plaintextL.grid(row=3, column=0)
ciphertextL=Label(root, text="Ciphertext", font=("Arial", 12))
ciphertextL.grid(row=3, column=1)

plaintextE=Text(root, width=100, height=10)
ciphertextE=Text(root, width=100, height=10)
plaintextE.grid(row=4, column=0)
ciphertextE.grid(row=4, column=1)

button_font = ("Arial", 12)
button_padx = 10
button_pady = 10

encryptB = Button(root, font=button_font, padx=button_padx, pady=button_pady, text="Encrypt",
                       command=lambda: caesar_e(plaintextE.get("1.0", "end-1c"),keyLg.get()))
encryptB.grid(row=5, column=0, sticky="we")

decryptB = Button(root, font=button_font, padx=button_padx, pady=button_pady, text="Decrypt",
                       command=lambda: caesar_d(ciphertextE.get("1.0", "end-1c"),keyLg.get()))

decryptB.grid(row=5, column=1, sticky="we")

clear=Button(root, font=button_font, padx=button_padx, pady=button_pady, text="Clear both",
                       command=lambda: delete())
clear.grid(row=6, column=0, sticky="we", columnspan=2)

combo.bind("<<ComboboxSelected>>", change_screen)
root.mainloop()  